version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/audio-converter
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgrespw
      GOOGLE_APPLICATION_CREDENTIALS: /app/audio_converter_key.json
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      FFMPEG_PATH: /usr/bin/ffmpeg
    volumes:
          - ./audio_converter_key.json:/app/audio_converter_key.json
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: audio-converter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    ports:
      - "5432:5432"